name: Zip and Upload to Chrome Web Store

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - src/manifest.json

jobs:
  upload-zip:
    runs-on: ubuntu-latest

    env:
      ZIP_FILE: src.zip

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Zip Source Directory Contents
      run: |
        cd src
        zip -r ../${{ env.ZIP_FILE }} .
        cd ..

    - name: Upload to Chrome Web Store
      uses: mobilefirstllc/cws-publish@latest
      with:
        action: 'upload'  # one of: upload, publish, testers
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        refresh_token: ${{ secrets.REFRESH_TOKEN }}
        extension_id: ${{ secrets.CHROME_EXTENSION_ID }} 
        zip_file: ${{ env.ZIP_FILE }}
